//import { applySourceSpanToStatementIfNeeded } from '@angular/compiler/src/output/output_ast';
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, UrlTree, Router } from '@angular/router';
//import { nextTick } from 'process';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AlbumDetailGuard implements CanActivate {
  // prev boiler plate code generated by ng g g albums/album-detail
  constructor(private router: Router) { }
  // following generated by ng g g albums/album-detail
  canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
    //
      let id = +route.url[1].path;   // it's next a.o.t. route in course....
      if(isNaN(id) || id < 1){
        alert("Invalid album ID");   // shoould route to an error page
        this.router.navigate(['/albums']);
        return false;
      }
    //
    return true;
  }

}
